version: '3.9'

services:
  checkcle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: checkcle
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - /var/pb_data:/mnt/pb_data  # Updated mount target to match CMD in Dockerfile
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
